// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RO
{
    
    
    public class KeepCodeFromStrip
    {
        
        public UnityEngine.Transform type2716414652;
        
        public MoonSerializable.DataCell type31833114;
        
        public UnityEngine.RectTransform type3322015850;
        
        public UnityEngine.Canvas type2741190556;
        
        public UnityEngine.UI.GraphicRaycaster type2425381644;
        
        public UnityEngine.CanvasRenderer type96051219;
        
        public UnityEngine.UI.RawImage type4074996845;
        
        public UnityEngine.UI.Image type90598499;
        
        public UnityEngine.UI.Button type2725987484;
        
        public UnityEngine.Animator type219573755;
        
        public UnityEngine.UI.Text type3132773;
        
        public UnityEngine.UI.Outline type3667161536;
        
        public MoonCommonLib.FxTimer type713237375;
        
        public UnityEngine.ParticleSystem type1523982201;
        
        public UnityEngine.ParticleSystemRenderer type84479216;
        
        public FxAnimation.FxAnimationHelper type2284668062;
        
        public UnityEngine.MeshFilter type1047783571;
        
        public UnityEngine.MeshRenderer type2378577796;
        
        public FollowObject type117528426;
        
        public UnityEngine.BoxCollider type4132860951;
        
        public UnityEngine.SkinnedMeshRenderer type1815164752;
        
        public Cinemachine.CinemachineVirtualCamera type2402051364;
        
        public Cinemachine.CinemachinePipeline type1085485162;
        
        public TMPro.TextMeshProUGUI type2054427421;
        
        public UnityEngine.UI.InputField type3547022196;
        
        public UnityEngine.UI.RectMask2D type973949744;
        
        public UnityEngine.UI.VerticalLayoutGroup type3257062181;
        
        public UnityEngine.UI.ContentSizeFitter type980904964;
        
        public UnityEngine.UI.LayoutElement type4081621224;
        
        public UnityEngine.UI.HorizontalLayoutGroup type2624611893;
        
        public UnityEngine.UI.ScrollRect type4112257341;
        
        public UnityEngine.UI.Mask type2876684;
        
        public PushToCommandBuffer type572508380;
        
        public UnityEngine.UI.Shadow type3375171974;
        
        public UnityEngine.CanvasGroup type2674694089;
        
        public FaceToCameraObj type1502633238;
        
        public UnityEngine.UI.GridLayoutGroup type965829041;
        
        public UnityEngine.TrailRenderer type1077352595;
        
        public Cinemachine.CinemachineBasicMultiChannelPerlin type710091460;
        
        public UnityEngine.UI.Toggle type3422827586;
        
        public UnityEngine.UI.Slider type3380202819;
        
        public DG.Tweening.DOTweenAnimation type1366232086;
        
        public UnityEngine.CapsuleCollider type3160482843;
        
        public Spine.Unity.SkeletonAnimation type3750219653;
        
        public UnityEngine.LensFlare type4024532028;
        
        public FaceToCamera type4183263707;
        
        public UnityEngine.LineRenderer type10192511;
        
        public UnityEngine.MeshCollider type3013183131;
        
        public UnityEngine.Animation type2950960096;
        
        public FaceToCameraObjPrepareData type3842047391;
        
        public UnityEngine.UI.Scrollbar type1946738500;
        
        public UnityEngine.UI.ToggleGroup type3657327663;
        
        public UnityEngine.Playables.PlayableDirector type1386777318;
        
        public Cinemachine.CinemachineComposer type151138236;
        
        public Cinemachine.CinemachineTransposer type1351579493;
        
        public MoonCommonLib.FxDistortion type3456925261;
        
        public UnityEngine.Camera type2741136649;
        
        public UnityEngine.FlareLayer type4243824999;
        
        public MoonSerializable.MCameraLayerCullingInfo type360770317;
        
        public UnityEngine.Projector type4216534904;
        
        public UnityEngine.UI.CanvasScaler type2816881750;
        
        public UnityEngine.EventSystems.EventSystem type4094435559;
        
        public UnityEngine.EventSystems.StandaloneInputModule type1709341407;
        
        public UnityEngine.SpriteRenderer type1281466702;
        
        public UnityEngine.UI.Dropdown type335261133;
        
        public ProjectorCacheMaterial type3952839515;
        
        //public FMODUnity.StudioEventEmitter type4073961524;
        
        public UIMesh type3415961675;
        
        public MoonSerializable.DataAssembly type628672346;
        
        public UnityEngine.LODGroup type2292708300;
        
        public MyFPSCounter type236046863;
        
        public MyFPSDisplay type1290393669;
        
        public UnityEngine.UI.AspectRatioFitter type1868418221;
        
        public Spine.Unity.SkeletonGraphic type2385771331;
        
        public MoonSerializable.SpriteAssembly type3715224695;
        
        public MoonSerializable.FontAssembly type1601071095;
    }
}
