# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RoToolMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 111, 21))
        self.label.setAcceptDrops(False)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(670, 40, 75, 21))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 70, 691, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 4)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 180, 151, 21))
        self.label_2.setObjectName("label_2")
        self.openCsvFloderBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openCsvFloderBtn.setGeometry(QtCore.QRect(50, 210, 121, 23))
        self.openCsvFloderBtn.setObjectName("openCsvFloderBtn")
        self.openBatToolFloderBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openBatToolFloderBtn.setGeometry(QtCore.QRect(190, 210, 161, 23))
        self.openBatToolFloderBtn.setObjectName("openBatToolFloderBtn")
        self.openRoPcPackage = QtWidgets.QPushButton(self.centralwidget)
        self.openRoPcPackage.setGeometry(QtCore.QRect(360, 210, 121, 23))
        self.openRoPcPackage.setObjectName("openRoPcPackage")
        self.openClientCodeFolder = QtWidgets.QPushButton(self.centralwidget)
        self.openClientCodeFolder.setGeometry(QtCore.QRect(500, 210, 221, 23))
        self.openClientCodeFolder.setObjectName("openClientCodeFolder")
        self.openCsvToolBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openCsvToolBtn.setGeometry(QtCore.QRect(50, 250, 121, 23))
        self.openCsvToolBtn.setObjectName("openCsvToolBtn")
        self.openProtoGenTool = QtWidgets.QPushButton(self.centralwidget)
        self.openProtoGenTool.setGeometry(QtCore.QRect(190, 250, 131, 23))
        self.openProtoGenTool.setObjectName("openProtoGenTool")
        self.buildPcDllBtn = QtWidgets.QPushButton(self.centralwidget)
        self.buildPcDllBtn.setGeometry(QtCore.QRect(340, 250, 121, 23))
        self.buildPcDllBtn.setObjectName("buildPcDllBtn")
        self.exportOfflineDataBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exportOfflineDataBtn.setGeometry(QtCore.QRect(480, 250, 121, 23))
        self.exportOfflineDataBtn.setObjectName("exportOfflineDataBtn")
        self.openLocalServerFolder = QtWidgets.QPushButton(self.centralwidget)
        self.openLocalServerFolder.setGeometry(QtCore.QRect(610, 250, 121, 23))
        self.openLocalServerFolder.setObjectName("openLocalServerFolder")
        self.openNavTool = QtWidgets.QPushButton(self.centralwidget)
        self.openNavTool.setGeometry(QtCore.QRect(50, 290, 121, 23))
        self.openNavTool.setObjectName("openNavTool")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 320, 151, 21))
        self.label_3.setObjectName("label_3")
        self.checkoutNewBranchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.checkoutNewBranchBtn.setGeometry(QtCore.QRect(260, 370, 151, 23))
        self.checkoutNewBranchBtn.setObjectName("checkoutNewBranchBtn")
        self.clearUntrackFileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearUntrackFileBtn.setGeometry(QtCore.QRect(420, 370, 151, 23))
        self.clearUntrackFileBtn.setObjectName("clearUntrackFileBtn")
        self.checkoutBranchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.checkoutBranchBtn.setGeometry(QtCore.QRect(580, 370, 121, 23))
        self.checkoutBranchBtn.setObjectName("checkoutBranchBtn")
        self.clearAndCheckoutBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearAndCheckoutBtn.setGeometry(QtCore.QRect(420, 410, 251, 23))
        self.clearAndCheckoutBtn.setObjectName("clearAndCheckoutBtn")
        self.pushToRemoteBtn = QtWidgets.QPushButton(self.centralwidget)
        self.pushToRemoteBtn.setGeometry(QtCore.QRect(260, 410, 151, 23))
        self.pushToRemoteBtn.setObjectName("pushToRemoteBtn")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(39, 360, 171, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.canOperaGitReposLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.canOperaGitReposLayout.setContentsMargins(0, 0, 0, 0)
        self.canOperaGitReposLayout.setObjectName("canOperaGitReposLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 340, 158, 21))
        self.label_4.setObjectName("label_4")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ro工具管理器"))
        self.label.setText(_translate("MainWindow", "sys_env.json路径："))
        self.pushButton.setText(_translate("MainWindow", "添加"))
        self.label_2.setText(_translate("MainWindow", "常用功能快捷入口："))
        self.openCsvFloderBtn.setText(_translate("MainWindow", "一键打开CSV文件夹"))
        self.openBatToolFloderBtn.setText(_translate("MainWindow", "一键打开BatTool文件夹"))
        self.openRoPcPackage.setText(_translate("MainWindow", "启动Ro PC包"))
        self.openClientCodeFolder.setText(_translate("MainWindow", "打开ClientCode工程文件目录"))
        self.openCsvToolBtn.setText(_translate("MainWindow", "启动CSV打表工具"))
        self.openProtoGenTool.setText(_translate("MainWindow", "打开Proto生成工具"))
        self.buildPcDllBtn.setText(_translate("MainWindow", "打Dll批处理工具"))
        self.exportOfflineDataBtn.setText(_translate("MainWindow", "导出离线表工具"))
        self.openLocalServerFolder.setText(_translate("MainWindow", "本地服相关工具"))
        self.openNavTool.setText(_translate("MainWindow", "寻路导航工具"))
        self.label_3.setText(_translate("MainWindow", "GIT常用组合操作入口："))
        self.checkoutNewBranchBtn.setText(_translate("MainWindow", "一键创建并切入新分支"))
        self.clearUntrackFileBtn.setText(_translate("MainWindow", "一键清空untracked文件"))
        self.checkoutBranchBtn.setText(_translate("MainWindow", "一键切入指定分支"))
        self.clearAndCheckoutBtn.setText(_translate("MainWindow", "一键Reset、Clean并切入新的分支同时拉取"))
        self.pushToRemoteBtn.setText(_translate("MainWindow", "一键push(推送到远端)"))
        self.label_4.setText(_translate("MainWindow", "勾选要操作的库："))
