---@class MoonClient.MCameraState : System.Enum
---@field public value__ number
---@field public Null number
---@field public Normal number
---@field public Photo number
---@field public SelfPhoto number
---@field public VR360Photo number
---@field public ARPhoto number
---@field public CountDownPhoto number
---@field public Npc number
---@field public Trigger number
---@field public Fixed number
---@field public OffSet number
---@field public FixedAngle number
---@field public Adaptive number
---@field public Refine number
---@field public ThemeDungeon number
---@field public SelectChar number
---@field public RoamScene number
---@field public FixedApproach number
---@field public Theater number
---@field public CameraStateCount number

---@type MoonClient.MCameraState
MoonClient.MCameraState = { }
