//this source code was auto-generated by tolua#, do not modify it
using System;
using MoonCommonLib;
using LuaInterface;

public class FaceToCameraObjPrepareDataWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FaceToCameraObjPrepareData), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("CustomActive", CustomActive);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("FaceToCameraObjs", get_FaceToCameraObjs, set_FaceToCameraObjs);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CustomActive(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			FaceToCameraObjPrepareData obj = (FaceToCameraObjPrepareData)ToLua.CheckObject<FaceToCameraObjPrepareData>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.CustomActive(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FaceToCameraObjs(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FaceToCameraObjPrepareData obj = (FaceToCameraObjPrepareData)o;
			FaceToCameraObj[] ret = obj.FaceToCameraObjs;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index FaceToCameraObjs on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_FaceToCameraObjs(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FaceToCameraObjPrepareData obj = (FaceToCameraObjPrepareData)o;
			FaceToCameraObj[] arg0 = ToLua.CheckObjectArray<FaceToCameraObj>(L, 2);
			obj.FaceToCameraObjs = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index FaceToCameraObjs on a nil value");
		}
	}
}

