//this source code was auto-generated by tolua#, do not modify it
using System;
using MoonCommonLib;
using LuaInterface;

public class RenderHeads_Media_AVProVideo_DisplayUGUIWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(RenderHeads.Media.AVProVideo.DisplayUGUI), typeof(UnityEngine.UI.MaskableGraphic));
		L.RegFunction("HasValidTexture", HasValidTexture);
		L.RegFunction("SetNativeSize", SetNativeSize);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("_mediaPlayer", get__mediaPlayer, set__mediaPlayer);
		L.RegVar("m_UVRect", get_m_UVRect, set_m_UVRect);
		L.RegVar("_setNativeSize", get__setNativeSize, set__setNativeSize);
		L.RegVar("_scaleMode", get__scaleMode, set__scaleMode);
		L.RegVar("_noDefaultDisplay", get__noDefaultDisplay, set__noDefaultDisplay);
		L.RegVar("_displayInEditor", get__displayInEditor, set__displayInEditor);
		L.RegVar("_defaultTexture", get__defaultTexture, set__defaultTexture);
		L.RegVar("mainTexture", get_mainTexture, null);
		L.RegVar("CurrentMediaPlayer", get_CurrentMediaPlayer, set_CurrentMediaPlayer);
		L.RegVar("uvRect", get_uvRect, set_uvRect);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int HasValidTexture(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)ToLua.CheckObject<RenderHeads.Media.AVProVideo.DisplayUGUI>(L, 1);
			bool o = obj.HasValidTexture();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetNativeSize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)ToLua.CheckObject<RenderHeads.Media.AVProVideo.DisplayUGUI>(L, 1);
			obj.SetNativeSize();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__mediaPlayer(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			RenderHeads.Media.AVProVideo.MediaPlayer ret = obj._mediaPlayer;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _mediaPlayer on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_UVRect(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			UnityEngine.Rect ret = obj.m_UVRect;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_UVRect on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__setNativeSize(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			bool ret = obj._setNativeSize;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _setNativeSize on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__scaleMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			UnityEngine.ScaleMode ret = obj._scaleMode;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _scaleMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__noDefaultDisplay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			bool ret = obj._noDefaultDisplay;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _noDefaultDisplay on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__displayInEditor(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			bool ret = obj._displayInEditor;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _displayInEditor on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__defaultTexture(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			UnityEngine.Texture ret = obj._defaultTexture;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _defaultTexture on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mainTexture(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			UnityEngine.Texture ret = obj.mainTexture;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mainTexture on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CurrentMediaPlayer(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			RenderHeads.Media.AVProVideo.MediaPlayer ret = obj.CurrentMediaPlayer;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrentMediaPlayer on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_uvRect(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			UnityEngine.Rect ret = obj.uvRect;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index uvRect on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__mediaPlayer(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			RenderHeads.Media.AVProVideo.MediaPlayer arg0 = (RenderHeads.Media.AVProVideo.MediaPlayer)ToLua.CheckObject<RenderHeads.Media.AVProVideo.MediaPlayer>(L, 2);
			obj._mediaPlayer = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _mediaPlayer on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_UVRect(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			UnityEngine.Rect arg0 = StackTraits<UnityEngine.Rect>.Check(L, 2);
			obj.m_UVRect = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_UVRect on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__setNativeSize(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj._setNativeSize = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _setNativeSize on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__scaleMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			UnityEngine.ScaleMode arg0 = (UnityEngine.ScaleMode)ToLua.CheckObject(L, 2, typeof(UnityEngine.ScaleMode));
			obj._scaleMode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _scaleMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__noDefaultDisplay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj._noDefaultDisplay = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _noDefaultDisplay on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__displayInEditor(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj._displayInEditor = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _displayInEditor on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__defaultTexture(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			UnityEngine.Texture arg0 = (UnityEngine.Texture)ToLua.CheckObject<UnityEngine.Texture>(L, 2);
			obj._defaultTexture = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _defaultTexture on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CurrentMediaPlayer(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			RenderHeads.Media.AVProVideo.MediaPlayer arg0 = (RenderHeads.Media.AVProVideo.MediaPlayer)ToLua.CheckObject<RenderHeads.Media.AVProVideo.MediaPlayer>(L, 2);
			obj.CurrentMediaPlayer = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrentMediaPlayer on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_uvRect(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			RenderHeads.Media.AVProVideo.DisplayUGUI obj = (RenderHeads.Media.AVProVideo.DisplayUGUI)o;
			UnityEngine.Rect arg0 = StackTraits<UnityEngine.Rect>.Check(L, 2);
			obj.uvRect = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index uvRect on a nil value");
		}
	}
}

