//this source code was auto-generated by tolua#, do not modify it
using System;
using MoonCommonLib;
using LuaInterface;

public class SDKLib_SDKInterface_EDevicePermissionResultWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(SDKLib.SDKInterface.EDevicePermissionResult));
		L.RegVar("None", get_None, null);
		L.RegVar("Authorized", get_Authorized, null);
		L.RegVar("Denied", get_Denied, null);
		L.RegVar("NotDetermined", get_NotDetermined, null);
		L.RegVar("DeniedAndNoAsk", get_DeniedAndNoAsk, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<SDKLib.SDKInterface.EDevicePermissionResult>.Check = CheckType;
		StackTraits<SDKLib.SDKInterface.EDevicePermissionResult>.Push = Push;
	}

	static void Push(IntPtr L, SDKLib.SDKInterface.EDevicePermissionResult arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(SDKLib.SDKInterface.EDevicePermissionResult), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, SDKLib.SDKInterface.EDevicePermissionResult.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Authorized(IntPtr L)
	{
		ToLua.Push(L, SDKLib.SDKInterface.EDevicePermissionResult.Authorized);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Denied(IntPtr L)
	{
		ToLua.Push(L, SDKLib.SDKInterface.EDevicePermissionResult.Denied);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NotDetermined(IntPtr L)
	{
		ToLua.Push(L, SDKLib.SDKInterface.EDevicePermissionResult.NotDetermined);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DeniedAndNoAsk(IntPtr L)
	{
		ToLua.Push(L, SDKLib.SDKInterface.EDevicePermissionResult.DeniedAndNoAsk);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		SDKLib.SDKInterface.EDevicePermissionResult o = (SDKLib.SDKInterface.EDevicePermissionResult)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

