---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richardjiang.
--- DateTime: 2018/9/13 14:09
---

module("Stage", package.seeall)
require "Stage/StageBase"

local super = Stage.StageBase
StageRingPre = class("StageRingPre", super)

function StageRingPre:ctor()
    super.ctor(self, MStageEnum.RingPre)
end

function StageRingPre:OnEnterStage(toSceneId, fromStage)
    super.OnEnterStage(self, toSceneId, fromStage)
    MgrMgr:GetMgr("ArenaMgr").EnterWaitingArena()
end

function StageRingPre:ActiveMainPanels()
    super.ActiveMainPanels(self)
    UIMgr:ActiveUI(UI.CtrlNames.BattleArena)
end

function StageRingPre:OnLeaveStage()
    super.OnLeaveStage(self)
    MgrMgr:GetMgr("ArenaMgr").LeaveWaitingArena()
end

